# Generated by Django 4.0.3 on 2022-06-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_header_img_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
